#!/usr/bin/env python3
"""
Supervised pre-training of the PointNet grasp-position predictor.

Trains PointNet to regress the 3D center of the best antipodal grasp
on each object, using the labels generated by generate_meshes.py.

Loss: for each sample, predict a grasp center; minimize the distance
to the NEAREST labeled grasp center (since many grasps are valid).

This gives the RL policy a warm start so it doesn't have to discover
graspable regions from a completely random initialization.

Usage:
    ./rl_unitree/bin/python scripts/pretrain_grasp.py
    ./rl_unitree/bin/python scripts/pretrain_grasp.py --data data/objects/train --epochs 200
"""

import argparse
import glob
import json
import os
import random

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from models.pointnet_encoder import PointNetEncoder


# ── Dataset ───────────────────────────────────────────────────────────────────

class GraspDataset(Dataset):
    """
    Loads (point_cloud, grasp_centers) pairs from disk.

    Each sample returns:
        pc       : (N, 3) float32  — sub-sampled point cloud in object frame
        grasps   : (K, 3) float32  — labeled grasp centers (top-K by quality)
    """

    def __init__(self, data_dir: str, n_pts: int = 128, n_grasp: int = 10,
                 augment: bool = True):
        self.n_pts    = n_pts
        self.n_grasp  = n_grasp
        self.augment  = augment
        self.samples  = []   # list of (pc_path, grasps_path)

        for pc_path in sorted(glob.glob(os.path.join(data_dir, "**/*_pc.npy"),
                                         recursive=True)):
            base   = pc_path.replace("_pc.npy", "")
            g_path = base + "_grasps.json"
            if os.path.exists(g_path):
                self.samples.append((pc_path, g_path))

        if not self.samples:
            raise RuntimeError(f"No (pc, grasp) pairs found under {data_dir}")
        print(f"[GraspDataset] {len(self.samples)} samples in {data_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        pc_path, g_path = self.samples[idx]

        # Load pre-sampled PC (512, 3) and sub-sample to n_pts
        pc_full = np.load(pc_path).astype(np.float32)  # (512, 3)
        chosen  = np.random.choice(len(pc_full), self.n_pts, replace=False)
        pc      = pc_full[chosen]   # (n_pts, 3)

        # Load grasp centers (take top-n_grasp by quality)
        with open(g_path) as f:
            data = json.load(f)
        grasp_list = data["grasps"] if isinstance(data, dict) else data
        grasps  = sorted(grasp_list, key=lambda g: g["quality"], reverse=True)
        grasps  = grasps[:self.n_grasp]
        centers = np.array([g["center"] for g in grasps], dtype=np.float32)

        if len(centers) == 0:
            # No antipodal grasps found — fall back to point-cloud centroid.
            centers = pc.mean(axis=0, keepdims=True)

        # Pad/truncate to fixed n_grasp so DataLoader can batch consistently.
        if len(centers) < self.n_grasp:
            pad = np.repeat(centers[-1:], self.n_grasp - len(centers), axis=0)
            centers = np.vstack([centers, pad])
        else:
            centers = centers[:self.n_grasp]

        # Augmentation: random rotation around vertical axis (Z)
        if self.augment:
            angle = np.random.uniform(0, 2 * np.pi)
            R = np.array([[np.cos(angle), -np.sin(angle), 0],
                           [np.sin(angle),  np.cos(angle), 0],
                           [0,              0,             1]], dtype=np.float32)
            pc      = (R @ pc.T).T
            centers = (R @ centers.T).T

        return (
            torch.from_numpy(np.ascontiguousarray(pc)),
            torch.from_numpy(np.ascontiguousarray(centers)),
        )


# ── Min-distance loss ─────────────────────────────────────────────────────────

def min_dist_loss(pred: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    """
    pred    : (B, 3)    — predicted grasp center
    targets : (B, K, 3) — K labeled grasp centers per sample
    Returns scalar loss = mean of min distance to any labeled grasp.
    """
    # (B, K, 3) - (B, 1, 3) → (B, K, 3)
    diff  = targets - pred.unsqueeze(1)
    dists = diff.norm(dim=-1)           # (B, K)
    min_d = dists.min(dim=-1).values    # (B,)
    return min_d.mean()


# ── Training ──────────────────────────────────────────────────────────────────

def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[pretrain] device={device}")

    dataset = GraspDataset(args.data, n_pts=args.n_pts, n_grasp=args.n_grasp,
                           augment=not args.no_augment)
    loader  = DataLoader(dataset, batch_size=args.batch, shuffle=True,
                         num_workers=2, pin_memory=(device.type == "cuda"))

    # PointNet encoder + small MLP head for position prediction
    encoder = PointNetEncoder(embed_dim=args.embed_dim).to(device)
    head    = nn.Sequential(
        nn.Linear(args.embed_dim, 128), nn.ELU(),
        nn.Linear(128, 64),             nn.ELU(),
        nn.Linear(64, 3),
    ).to(device)

    params    = list(encoder.parameters()) + list(head.parameters())
    optimizer = torch.optim.Adam(params, lr=args.lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, args.epochs)

    os.makedirs(args.out, exist_ok=True)
    best_loss = float("inf")

    for epoch in range(1, args.epochs + 1):
        epoch_loss = 0.0
        for pc, grasps in loader:
            pc     = pc.to(device)       # (B, N, 3)
            grasps = grasps.to(device)   # (B, K, 3)

            feat = encoder(pc)           # (B, embed_dim)
            pred = head(feat)            # (B, 3)

            loss = min_dist_loss(pred, grasps)
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(params, 1.0)
            optimizer.step()
            epoch_loss += loss.item()

        scheduler.step()
        avg = epoch_loss / len(loader)

        if epoch % 10 == 0 or epoch == 1:
            print(f"  epoch {epoch:4d}/{args.epochs}  loss={avg:.4f}  "
                  f"lr={scheduler.get_last_lr()[0]:.2e}")

        if avg < best_loss:
            best_loss = avg
            save_path = os.path.join(args.out, "grasp_pretrain_best.pt")
            torch.save({
                "encoder": encoder.state_dict(),
                "head":    head.state_dict(),
                "epoch":   epoch,
                "loss":    avg,
                "embed_dim": args.embed_dim,
                "n_pts":     args.n_pts,
            }, save_path)

    final_path = os.path.join(args.out, "grasp_pretrain_final.pt")
    torch.save({
        "encoder": encoder.state_dict(),
        "head":    head.state_dict(),
        "epoch":   args.epochs,
        "loss":    avg,
        "embed_dim": args.embed_dim,
        "n_pts":     args.n_pts,
    }, final_path)

    print(f"\n[pretrain] done.  best loss={best_loss:.4f}")
    print(f"  best  → {os.path.join(args.out, 'grasp_pretrain_best.pt')}")
    print(f"  final → {final_path}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--data",        default="data/objects/train")
    p.add_argument("--out",         default="data/grasp_weights")
    p.add_argument("--epochs",      type=int,   default=150)
    p.add_argument("--batch",       type=int,   default=64)
    p.add_argument("--lr",          type=float, default=1e-3)
    p.add_argument("--n_pts",       type=int,   default=128)
    p.add_argument("--n_grasp",     type=int,   default=10)
    p.add_argument("--embed_dim",   type=int,   default=128)
    p.add_argument("--no_augment",  action="store_true")
    args = p.parse_args()
    train(args)


if __name__ == "__main__":
    main()
